// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1.CQRS_MediatR_Using_gRPC.Data;

#nullable disable

namespace Task1.CQRS_MediatR_Using_gRPC.Data.Migrations
{

}
